services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: space-edu-3d:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"
    restart: unless-stopped